/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'matthiasgramm' at '21.01.17 18:36' with Gradle 2.14.1
 *
 * @author matthiasgramm, @date 21.01.17 18:36
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
